#!/bin/bash

set -Eeuo pipefail

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.go$" || true)

function make-fmt() {
  # only format if Go files have changed
  if [ -n "$STAGED_GO_FILES" ]; then
    echo 'Running `make fmt`.'
    make fmt
    git add -A
    echo 'Formatting completed.'
  fi
}

function make-lint() {
  # only lint if Go files have changed
  if [ -n "$STAGED_GO_FILES" ]; then
    echo 'Running `make lint`.'
    make lint
    echo 'Lint completed.'
  fi
}

function semgrep-scan() {
  echo 'Running `make semgrep`.'
  make semgrep SEMGREP_FLAGS=--verbose
}

function secrets-scan() {
  echo 'Running secrets scan with gitleaks.'
  gitleaks git --verbose --pre-commit
}

function failed {
  echo ''
  echo -e "pre-commit hook failed... You cannot commit!"
  echo ''

  exit 1
}

trap 'failed' ERR

make-fmt
make-lint
semgrep-scan
secrets-scan
